Add /bigobj option
Without this option, fatal error C1128 prevents compilation due to the
object file format size limit while compiling as a shared library.